from models.models import *
from pririgardus import *

pais_arg = Pais(descripcion='Argentina')
prov_sta = Provincia(descripcion='Santa Fe', pais=pais_arg)
dep_ros = Departamento(descripcion='Rosario', provincia=prov_sta)
loc_ros = Localidad(descripcion='Rosario', departamento=dep_ros)

db.session.add_all([pais_arg, prov_sta, dep_ros, loc_ros])

mesanum = 6000
esccir = [['Rep Paraguay', 'Malvinas', 'Normal 1'], ['Normal 3', 'Moreno']]
for secnum in range(1, 22):
    secc = Seccional(numero=str(secnum), localidad=loc_ros)
    db.session.add(secc)
    for cirnum in range(1, 2):
        circ = Circuito(descripcion='Circuito ' + str(cirnum), seccional=secc)
        db.session.add(circ)
        for escnom in esccir[cirnum - 1]:
            esc = Escuela(descripcion=escnom, circuito=circ)
            db.session.add(esc)
            for i in range(1, 3):
                mesa = Mesa(numero=mesanum, escuela=esc)
                mesanum += 1
                db.session.add(mesa)

tipocargos = TipoCargo.query.all()
gobierno = Cargo_Provincial(prov_sta, tipocargos[3])
diputado = Cargo_Provincial(prov_sta, tipocargos[4])
senador = Cargo_Departamental(dep_ros, tipocargos[5])
intendencia = Cargo_Local(loc_ros, tipocargos[6])
concejal = Cargo_Local(loc_ros, tipocargos[7])
db.session.add_all([concejal, intendencia, senador, diputado, gobierno])
db.session.commit()

db.session.add(Frente(9033, 'FRENTE DE IZQUIERDA Y DE LOS TRABAJADORES'))
db.session.add(Frente(9031, 'FRENTE DE LA CULTURA, LA EDUCACION Y EL TRABAJO'))
db.session.add(Frente(9032, 'FRENTE SOCIAL Y POPULAR'))
db.session.add(Frente(9041, 'FRENTE JUSTICIALISTA PARA LA VICTORIA'))
db.session.add(Frente(9039, 'UNION PRO FEDERAL'))
db.session.add(Frente(9029, 'FRENTE PROGRESISTA CIVICO Y SOCIAL'))
db.session.add(Frente(704, 'MOV. INDEPENDIENTE, JUSTICIA Y DIGNIDAD'))
db.session.add(Frente(9030, 'FRENTE RENOVADOR DE LA ESPERANZA'))
db.session.add(Frente(1089, 'PARA LA CIUDAD FUTURA'))
db.session.add(Frente(63, 'ES POSIBLE'))
db.session.add(Frente(65, 'PARTIDO UNION CELESTE Y BLANCO'))
db.session.add(Frente(8037, 'UNITE POR LA LIBERTAD Y LA DIGNIDAD'))
db.session.add(Lista(1, 1, 'FRENTE DE IZQUIERDA', db.session.query(Frente).filter(Frente.id == 9033).first(), intendencia))
db.session.add(Lista(2, 5, 'UNION POR EL TRABAJO Y LA LIBERTAD', db.session.query(Frente).filter(Frente.id == 9031).first(), intendencia))
db.session.add(Lista(2, 6, 'CAMBIO ROSARINO', db.session.query(Frente).filter(Frente.id == 9031).first(), intendencia))
db.session.add(Lista(3, 1, 'UNIDAD SOCIAL Y POPULAR', db.session.query(Frente).filter(Frente.id == 9032).first(), intendencia))
db.session.add(Lista(4, 42, 'ENCUENTRO SANTAFESINO', db.session.query(Frente).filter(Frente.id == 9041).first(), intendencia))
db.session.add(Lista(4, 86, 'PRIMERO SANTA FE', db.session.query(Frente).filter(Frente.id == 9041).first(), intendencia))
db.session.add(Lista(4, 100, 'FUERZA PARA LA VICTORIA', db.session.query(Frente).filter(Frente.id == 9041).first(), intendencia))
db.session.add(Lista(4, 137, 'VECINOS ROSARINOS', db.session.query(Frente).filter(Frente.id == 9041).first(), intendencia))
db.session.add(Lista(5, 1, 'MEJOR JUNTOS', db.session.query(Frente).filter(Frente.id == 9039).first(), intendencia))
db.session.add(Lista(6, 2, 'ADELANTE', db.session.query(Frente).filter(Frente.id == 9029).first(), intendencia))
db.session.add(Lista(6, 40, 'FIRMEZA PARA AVANZAR', db.session.query(Frente).filter(Frente.id == 9029).first(), intendencia))
db.session.add(Lista(7, 1, 'DIGNIDAD', db.session.query(Frente).filter(Frente.id == 704).first(), intendencia))
db.session.add(Lista(8, 3, '+ POR ROSARIO', db.session.query(Frente).filter(Frente.id == 9030).first(), intendencia))
db.session.add(Lista(14, 1, 'CIUDAD FUTURA', db.session.query(Frente).filter(Frente.id == 1089).first(), intendencia))
db.session.add(Lista(78, 2, 'ROSARIO ES POSIBLE', db.session.query(Frente).filter(Frente.id == 63).first(), intendencia))
db.session.add(Lista(1, 1, 'FRENTE DE IZQUIERDA', db.session.query(Frente).filter(Frente.id == 9033).first(), senador))
db.session.add(Lista(2, 5, 'UNION POR EL TRABAJO Y LA LIBERTAD', db.session.query(Frente).filter(Frente.id == 9031).first(), senador))
db.session.add(Lista(3, 1, 'UNIDAD SOCIAL Y POPULAR', db.session.query(Frente).filter(Frente.id == 9032).first(), senador))
db.session.add(Lista(4, 42, 'ENCUENTRO SANTAFESINO', db.session.query(Frente).filter(Frente.id == 9041).first(), senador))
db.session.add(Lista(4, 62, 'UNIDOS PODEMOS', db.session.query(Frente).filter(Frente.id == 9041).first(), senador))
db.session.add(Lista(4, 86, 'PRIMERO SANTA FE', db.session.query(Frente).filter(Frente.id == 9041).first(), senador))
db.session.add(Lista(4, 100, 'FUERZA PARA LA VICTORIA', db.session.query(Frente).filter(Frente.id == 9041).first(), senador))
db.session.add(Lista(5, 1, 'MEJOR JUNTOS', db.session.query(Frente).filter(Frente.id == 9039).first(), senador))
db.session.add(Lista(6, 2, 'ADELANTE', db.session.query(Frente).filter(Frente.id == 9029).first(), senador))
db.session.add(Lista(6, 17, 'EDUCACIÓN PARA CRECER', db.session.query(Frente).filter(Frente.id == 9029).first(), senador))
db.session.add(Lista(6, 23, 'GENERACION 83', db.session.query(Frente).filter(Frente.id == 9029).first(), senador))
db.session.add(Lista(6, 35, 'UNIDAD CAMBIO RESILIENCIA', db.session.query(Frente).filter(Frente.id == 9029).first(), senador))
db.session.add(Lista(6, 40, 'FIRMEZA PARA AVANZAR', db.session.query(Frente).filter(Frente.id == 9029).first(), senador))
db.session.add(Lista(7, 1, 'DIGNIDAD', db.session.query(Frente).filter(Frente.id == 704).first(), senador))
db.session.add(Lista(8, 4, 'CIEN POR CIENTO RENOVADOR', db.session.query(Frente).filter(Frente.id == 9030).first(), senador))
db.session.add(Lista(8, 7, 'MAS ACCION Y TRABAJO', db.session.query(Frente).filter(Frente.id == 9030).first(), senador))
db.session.add(Lista(9, 36, 'ROSARIO CELESTE Y BLANCO', db.session.query(Frente).filter(Frente.id == 65).first(), senador))
db.session.add(Lista(1, 1, 'FRENTE DE IZQUIERDA', db.session.query(Frente).filter(Frente.id == 9033).first(), concejal))
db.session.add(Lista(2, 1, 'POR UNA ROSARIO MEJOR', db.session.query(Frente).filter(Frente.id == 9031).first(), concejal))
db.session.add(Lista(2, 5, 'UNION POR EL TRABAJO Y LA LIBERTAD', db.session.query(Frente).filter(Frente.id == 9031).first(), concejal))
db.session.add(Lista(2, 6, 'CAMBIO ROSARINO', db.session.query(Frente).filter(Frente.id == 9031).first(), concejal))
db.session.add(Lista(3, 1, 'UNIDAD SOCIAL Y POPULAR', db.session.query(Frente).filter(Frente.id == 9032).first(), concejal))
db.session.add(Lista(4, 24, 'NACE UNA ESPERANZA', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 25, 'ROSARIO PARA LA VICTORIA', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 42, 'ENCUENTRO SANTAFESINO', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 44, 'UNA CIUDAD PARA TODOS', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 50, 'COMPROMETIDO CON ROSARIO', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 62, 'UNIDOS PODEMOS', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 86, 'PRIMERO SANTA FE', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 92, 'JUNTOS POR SANTA FE', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 100, 'FUERZA PARA LA VICTORIA', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 114, 'PRIMERO ROSARIO', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 132, 'AGRUPACIÓN VECINAL HOMBRE NUEVO', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(4, 137, 'VECINOS ROSARINOS', db.session.query(Frente).filter(Frente.id == 9041).first(), concejal))
db.session.add(Lista(5, 1, 'MEJOR JUNTOS', db.session.query(Frente).filter(Frente.id == 9039).first(), concejal))
db.session.add(Lista(6, 2, 'ADELANTE', db.session.query(Frente).filter(Frente.id == 9029).first(), concejal))
db.session.add(Lista(6, 8, 'POR LOS BARRIOS', db.session.query(Frente).filter(Frente.id == 9029).first(), concejal))
db.session.add(Lista(6, 9, 'ASAMBLEA PROGRESISTA', db.session.query(Frente).filter(Frente.id == 9029).first(), concejal))
db.session.add(Lista(6, 11, 'ARRIBA ROSARIO', db.session.query(Frente).filter(Frente.id == 9029).first(), concejal))
db.session.add(Lista(6, 20, 'SUMATE AL MOVIMIENTO', db.session.query(Frente).filter(Frente.id == 9029).first(), concejal))
db.session.add(Lista(6, 35, 'UNIDAD CAMBIO RESILIENCIA', db.session.query(Frente).filter(Frente.id == 9029).first(), concejal))
db.session.add(Lista(6, 40, 'FIRMEZA PARA AVANZAR', db.session.query(Frente).filter(Frente.id == 9029).first(), concejal))
db.session.add(Lista(6, 44, 'ROSARINOS INDEPENDIENTES', db.session.query(Frente).filter(Frente.id == 9029).first(), concejal))
db.session.add(Lista(6, 46, 'PODER DEL PUEBLO', db.session.query(Frente).filter(Frente.id == 9029).first(), concejal))
db.session.add(Lista(7, 1, 'DIGNIDAD', db.session.query(Frente).filter(Frente.id == 704).first(), concejal))
db.session.add(Lista(8, 3, '+ POR ROSARIO', db.session.query(Frente).filter(Frente.id == 9030).first(), concejal))
db.session.add(Lista(8, 7, 'MAS ACCION Y TRABAJO', db.session.query(Frente).filter(Frente.id == 9030).first(), concejal))
db.session.add(Lista(9, 2, 'CIUDAD AUTONOMA', db.session.query(Frente).filter(Frente.id == 65).first(), concejal))
db.session.add(Lista(9, 24, 'ROSARIO CELESTE Y BLANCO', db.session.query(Frente).filter(Frente.id == 65).first(), concejal))
db.session.add(Lista(10, 1, 'UNIDAD ROSARINA', db.session.query(Frente).filter(Frente.id == 8037).first(), concejal))
db.session.add(Lista(10, 2, 'ROSARIO SOLIDARIA Y POPULAR', db.session.query(Frente).filter(Frente.id == 8037).first(), concejal))
db.session.add(Lista(10, 3, 'HAY ESPERANZA PARA ROSARIO', db.session.query(Frente).filter(Frente.id == 8037).first(), concejal))
db.session.add(Lista(10, 5, 'ROSARIO MAS SEGURA', db.session.query(Frente).filter(Frente.id == 8037).first(), concejal))
db.session.add(Lista(14, 1, 'CIUDAD FUTURA', db.session.query(Frente).filter(Frente.id == 1089).first(), concejal))
db.session.add(Lista(78, 1, 'BIEN DE ROSARIO', db.session.query(Frente).filter(Frente.id == 63).first(), concejal))
db.session.add(Lista(78, 2, 'ROSARIO ES POSIBLE', db.session.query(Frente).filter(Frente.id == 63).first(), concejal))
db.session.add(Lista(78, 3, 'CIEN POR CIENTO ROSARIO', db.session.query(Frente).filter(Frente.id == 63).first(), concejal))
db.session.add(Lista(1, 1, 'FRENTE DE IZQUIERDA', db.session.query(Frente).filter(Frente.id == 9033).first(), diputado))
db.session.add(Lista(2, 3, 'CAMBIAR SANTA FE', db.session.query(Frente).filter(Frente.id == 9031).first(), diputado))
db.session.add(Lista(2, 5, 'UNION POR EL TRABAJO Y LA LIBERTAD', db.session.query(Frente).filter(Frente.id == 9031).first(), diputado))
db.session.add(Lista(3, 1, 'UNIDAD SOCIAL Y POPULAR', db.session.query(Frente).filter(Frente.id == 9032).first(), diputado))
db.session.add(Lista(4, 8, 'FRENTE POR LA JUSTICIA SOCIAL', db.session.query(Frente).filter(Frente.id == 9041).first(), diputado))
db.session.add(Lista(4, 48, 'DIGNIDAD PERONISTA', db.session.query(Frente).filter(Frente.id == 9041).first(), diputado))
db.session.add(Lista(4, 55, 'SOMOS SANTA FE', db.session.query(Frente).filter(Frente.id == 9041).first(), diputado))
db.session.add(Lista(4, 62, 'UNIDOS PODEMOS', db.session.query(Frente).filter(Frente.id == 9041).first(), diputado))
db.session.add(Lista(4, 86, 'PRIMERO SANTA FE', db.session.query(Frente).filter(Frente.id == 9041).first(), diputado))
db.session.add(Lista(4, 92, 'JUNTOS POR SANTA FE', db.session.query(Frente).filter(Frente.id == 9041).first(), diputado))
db.session.add(Lista(5, 1, 'MEJOR JUNTOS', db.session.query(Frente).filter(Frente.id == 9039).first(), diputado))
db.session.add(Lista(6, 2, 'ADELANTE', db.session.query(Frente).filter(Frente.id == 9029).first(), diputado))
db.session.add(Lista(6, 9, 'ASAMBLEA PROGRESISTA', db.session.query(Frente).filter(Frente.id == 9029).first(), diputado))
db.session.add(Lista(6, 17, 'EDUCACIÓN PARA CRECER', db.session.query(Frente).filter(Frente.id == 9029).first(), diputado))
db.session.add(Lista(6, 20, 'SUMATE AL MOVIMIENTO', db.session.query(Frente).filter(Frente.id == 9029).first(), diputado))
db.session.add(Lista(6, 27, 'RAZONES PARA CONFIAR', db.session.query(Frente).filter(Frente.id == 9029).first(), diputado))
db.session.add(Lista(6, 34, 'LIBRES DEL SUR', db.session.query(Frente).filter(Frente.id == 9029).first(), diputado))
db.session.add(Lista(6, 35, 'UNIDAD CAMBIO RESILIENCIA', db.session.query(Frente).filter(Frente.id == 9029).first(), diputado))
db.session.add(Lista(6, 39, 'SEGURIDAD TRABAJO Y HONESTIDAD', db.session.query(Frente).filter(Frente.id == 9029).first(), diputado))
db.session.add(Lista(6, 40, 'FIRMEZA PARA AVANZAR', db.session.query(Frente).filter(Frente.id == 9029).first(), diputado))
db.session.add(Lista(7, 1, 'DIGNIDAD', db.session.query(Frente).filter(Frente.id == 704).first(), diputado))
db.session.add(Lista(8, 4, 'CIEN POR CIENTO RENOVADOR', db.session.query(Frente).filter(Frente.id == 9030).first(), diputado))
db.session.add(Lista(8, 5, '+ AUSTERIDAD VECINALISTA', db.session.query(Frente).filter(Frente.id == 9030).first(), diputado))
db.session.add(Lista(8, 7, 'MAS ACCION Y TRABAJO', db.session.query(Frente).filter(Frente.id == 9030).first(), diputado))
db.session.add(Lista(9, 20, 'SANTA FE CELESTE Y BLANCO', db.session.query(Frente).filter(Frente.id == 65).first(), diputado))
db.session.add(Lista(10, 12, 'SER MAS', db.session.query(Frente).filter(Frente.id == 8037).first(), diputado))
db.session.add(Lista(1, 1, ' FRENTE DE IZQUIERDA', db.session.query(Frente).filter(Frente.id == 9033).first(), gobierno))
db.session.add(Lista(2, 5, ' UNION POR EL TRABAJO Y LA LIBERTAD', db.session.query(Frente).filter(Frente.id == 9031).first(), gobierno))
db.session.add(Lista(3, 1, ' UNIDAD SOCIAL Y POPULAR', db.session.query(Frente).filter(Frente.id == 9032).first(), gobierno))
db.session.add(Lista(4, 86, ' PRIMERO SANTA FE', db.session.query(Frente).filter(Frente.id == 9041).first(), gobierno))
db.session.add(Lista(5, 1, ' MEJOR JUNTOS', db.session.query(Frente).filter(Frente.id == 9039).first(), gobierno))
db.session.add(Lista(6, 2, ' ADELANTE', db.session.query(Frente).filter(Frente.id == 9029).first(), gobierno))
db.session.add(Lista(6, 40, ' FIRMEZA PARA AVANZAR', db.session.query(Frente).filter(Frente.id == 9029).first(), gobierno))
db.session.add(Lista(7, 1, ' Dignidad', db.session.query(Frente).filter(Frente.id == 704).first(), gobierno))
db.session.add(Lista(8, 4, ' CIEN POR CIENTO RENOVADOR', db.session.query(Frente).filter(Frente.id == 9030).first(), gobierno))
db.session.add(Lista(8, 7, ' Mas Accion y Trabajo', db.session.query(Frente).filter(Frente.id == 9030).first(), gobierno))
db.session.commit()